-- MySQL Script generated by MySQL Workbench
-- Fri Apr 10 23:19:53 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema circuler
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema circuler
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `circuler` DEFAULT CHARACTER SET utf8 ;
USE `circuler` ;

-- -----------------------------------------------------
-- Table `circuler`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `circuler`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `status` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE INDEX (`email` ASC) VISIBLE,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `circuler`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `circuler`.`roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `circuler`.`role_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `circuler`.`role_users` (
  `role_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`role_id`, `user_id`),
  INDEX `fk_role_users_1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_role_users_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `circuler`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_role_users_2`
    FOREIGN KEY (`role_id`)
    REFERENCES `circuler`.`roles` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `circuler`.`books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `circuler`.`books` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `author` VARCHAR(255) NOT NULL,
  `publisher` VARCHAR(100) NULL DEFAULT NULL,
  `thumbnail_url` VARCHAR(500) NULL DEFAULT NULL,
  `category` INT NOT NULL,
  `isbn` VARCHAR(45) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `circuler`.`collection_points`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `circuler`.`collection_points` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `address_street` VARCHAR(255) NOT NULL,
  `address_neighborhood` VARCHAR(100) NOT NULL,
  `capacity_limit` INT NOT NULL,
  `status` INT NOT NULL,
  `user_admin_id` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_collection_points_admin_idx` (`user_admin_id` ASC) VISIBLE,
  CONSTRAINT `fk_collection_points_admin`
    FOREIGN KEY (`user_admin_id`)
    REFERENCES `circuler`.`users` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `circuler`.`book_instances`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `circuler`.`book_instances` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `book_id` INT NOT NULL,
  `user_donor_id` INT NULL DEFAULT NULL,
  `current_point_id` INT NOT NULL,
  `status` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_book_instances_1_idx` (`book_id` ASC) VISIBLE,
  INDEX `fk_book_instances_2_idx` (`user_donor_id` ASC) VISIBLE,
  INDEX `fk_book_instances_3_idx` (`current_point_id` ASC) VISIBLE,
  CONSTRAINT `fk_book_instances_1`
    FOREIGN KEY (`book_id`)
    REFERENCES `circuler`.`books` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_book_instances_2`
    FOREIGN KEY (`user_donor_id`)
    REFERENCES `circuler`.`users` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_book_instances_3`
    FOREIGN KEY (`current_point_id`)
    REFERENCES `circuler`.`collection_points` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `circuler`.`reservations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `circuler`.`reservations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `book_instance_id` INT NOT NULL,
  `verification_code` VARCHAR(45) NOT NULL,
  `status` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_reservations_user_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_reservations_instance_idx` (`book_instance_id` ASC) VISIBLE,
  CONSTRAINT `fk_reservations_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `circuler`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_reservations_instance`
    FOREIGN KEY (`book_instance_id`)
    REFERENCES `circuler`.`book_instances` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
